#!/bin/bash

# This script shows how to run back-end only mode.

# You should provide feature message for each frame and a calibration file.
# Our program 'ice_ba' support generating feature message and calibration file.
# After running 'ice-ba' with flag 'save_feature', you will get feature message in your sequence folder: 
# 1. calibration.dat
# 2. a folder called 'dat' which contains .dat files that correspond to frames one by one

# For example, your dataset dir is /home/dataset/EuRoC/MH_01_easy
# Then run:
 
# ./bin/ice_ba --imgs_folder /home/dataset/EuRoC/MH_01_easy --start_idx 0 --end_idx -1 --iba_param_path ./config/config_of_stereo.txt  --gba_camera_save_path /home/dataset/EuRoC/result/MH_01_easy.txt --stereo --save_feature

# Then, there will be a calibration file: /home/dataset/EuRoC/calibration.dat,
# and a folder contains lots of dat files correspond to your input images one by one: /home/dataset/EuRoC/dat/*.dat

# Now, you can run back-end only by the following command
# If your feature message generated by monocular mode, use config_of_mono.txt as your config file. Otherwise, config_of_stereo.txt.
# Set your sequence path to 'input_directory' in config file. For the above example, the path should be: /home/dataset/EuRoC/MH_01_easy/
../bin/back_end ../config/config_of_stereo.txt



#此脚本显示如何运行仅后端模式。

#您应该为每个帧和校准文件提供功能消息。
#我们的程序'ice_ba'支持生成功能消息和校准文件。
#使用标记'save_feature'运行'ice-ba'后，您将在序列文件夹中获得功能消息：
#＃1. calibration.dat
#＃2。一个名为'dat'的文件夹，其中包含与逐个帧对应的.dat文件

#＃例如，您的数据集目录是/ home / dataset / EuRoC / MH_01_easy
#＃然后运行：
 
#＃。/ bin/ice_ba --imgs_folder / home / dataset / EuRoC / MH_01_easy --start_idx 0 --end_idx -1 --iba_param_path ./config/config_of_stereo.txt --gba_camera_save_path / home / dataset / EuRoC / result / MH_01_easy。 txt --stereo --save_feature

#＃然后，会有一个校准文件：/home/dataset/EuRoC/calibration.dat，
#＃和一个文件夹包含大量与您的输入图像对应的dat文件：/home/dataset/EuRoC/dat/*.dat

#＃现在，您只能通过以下命令运行后端
#＃如果您的功能消息是通过单眼模式生成的，请使用config_of_mono.txt作为配置文件。否则，config_of_stereo.txt。
#＃在配置文件中将序列路径设置为“input_directory”。对于上面的示例，路径应为：/ home / dataset / EuRoC / MH_01_easy /
